[Rainmeter]
Author		= Gnu32/Crome Tysnomi/Ayman Habayeb/Major Rasputin
@include1	= Internal\Common.inc

; Metadata included per-file because RainBrowser sucks ass
[Metadata]
Name			= CornerClock
Config			= CornerClock
Description		= A minimalist clock and date put aside to one corner
Instructions	= Read the readme for instructions, silly!
Version			= 1.5
Tags			= Time | Date | Minimalist | Corner | Personal
License			= Creative Commons Attribution-Share Alike 3.0 License.
Variant			= 
Preview			= 

[Variables]
@include2	= UserSettings.inc
FirstRunOnDesktopSet=0

[Measures]
@include3	= Internal\Measures.inc

[Meters]
@include4	= Internal\Meters.inc

; This is needed due to the container bug; to pad out the "window" so that the month string doesn't get clipped
[MSimWindow]
Meter=STRING
W=700
H=700

; Rainmeter has the weirdest, shittiest string rendering code ever
[MSimSecond]
X = 590
Y = 18

; See Readme for notes about this "hack"
TransformationMatrix=1;0;0;1;20;0

[MSimTime]
X = 619
Y = 3

[MSimDay]
X = 632
Y = 13
StringAlign	= Right

[MSimDate]
X = 280
Y = 35

[MSimMonth]
X = 0
Y = 0
Angle		= 1.57079633

; See Readme for notes about this "hack"
TransformationMatrix=1;0;0;1;706;65

[MSimPersonal]
X = 621
Y = 5
StringAlign	= Right
